name: Hello World Docker Action

inputs:
  who-to-greet:
    description: Who to greet in the log
    required: true
    default: 'World'
    type: string
outputs:
  current_time:
    description: The current time is
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
