name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Builds:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "The job was triggered by: ${{ github.event_name }}"
          echo "The job was triggered on branch: ${{ github.ref_name }}" 
      - uses: actions/checkout@v3.3.0
      - name: "List all files of repo:"
        run: |
          tree
  Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Builds
    environment: Test
    steps:
      - run: echo "Testing..."
  Load-Test:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: Builds
    environment: Load-Test
    steps:
      - run: |
          echo "Testing..."
          sleep 15
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: github.event.inputs.environment == 'Production' 
    steps:
      - run: |
          echo "Step 1 deploying..."
          sleep 10
      - run: |
          echo "Step 2 deploying..."
          sleep 10
      - run: |
          echo "Step 3 deploying..."
          sleep 10
      - run: |
          echo "Step 4 deploying..."
          sleep 10
      - run: |
          echo "Step 5 deploying..."
          sleep 10
    
